# Spring
spring.application.name=medical-clinic-proxy
server.port=8083

# Swagger
springdoc.api-docs.path=/api-docs

# Logger
logging.level.root=INFO
logging.level.neqrofukk.medical-clinic-proxy.demo=DEBUG
logging.level.liquibase=DEBUG

# ProblemDetails
spring.mvc.problemdetails.enabled=true

# Feign
spring.cloud.openfeign.client.config.default.connect-timeout=3000
spring.cloud.openfeign.client.config.default.read-timeout=5000
spring.cloud.openfeign.circuitbreaker.enabled=true